### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by jinli4114** [sunyifu/hellogit#2]
Your code is good, But before the main function you use void not int, the dev c++ can't run it, if I change it to int, Your program is prefect. What's more, you deal with the problem that we can't submit the code with Chinese. You are good.

**Comment by Clark5** [comment]
the input can be improved, that is we can input the number in a line with out space.
you are excellent!

**Comment by sunyifu** [comment]
Your comment is interesting. Anyway, I will reconsider it.
