### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by ShuangjiaMo** [sunyifu/hellogit#4]
You used "void main()" which cannot run in dev-c++.It is more routine to use "int".
The structure is very clear.And you code is easy for others to understand with notes. You did a great job on that!
If we enter the wrong input, the program will be closed. And we can only play the game for 1 time even if we enter "Y". Maybe you can improve that.

**Comment by sunyifu** [comment]
Your advice is considerable. I will solve it in no time.
